//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quick_Controls_V2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quick_Controls_V2.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Tiles/Volume.png.
        /// </summary>
        public static string iconImage {
            get {
                return ResourceManager.GetString("iconImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Background/.
        /// </summary>
        public static string ImageBackground {
            get {
                return ResourceManager.GetString("ImageBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Music/1quickstop.mp3.
        /// </summary>
        public static string Quickstop {
            get {
                return ResourceManager.GetString("Quickstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Tiles/Volume.png.
        /// </summary>
        public static string smallIconImage {
            get {
                return ResourceManager.GetString("smallIconImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTO-CLOSE MODE.
        /// </summary>
        public static string TextAutocloseMode {
            get {
                return ResourceManager.GetString("TextAutocloseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-close when lock button is pressed.
        /// </summary>
        public static string TextAutocloseModeDetail {
            get {
                return ResourceManager.GetString("TextAutocloseModeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASHLIGHT MODE.
        /// </summary>
        public static string TextFlashlightMode {
            get {
                return ResourceManager.GetString("TextFlashlightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable AUTO-CLOSE while flashlight is on.
        /// </summary>
        public static string TextFlashlightModeDetail {
            get {
                return ResourceManager.GetString("TextFlashlightModeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*) Give me 5* if you like.
        /// </summary>
        public static string TextGiveMeRate {
            get {
                return ResourceManager.GetString("TextGiveMeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter volume value.
        /// </summary>
        public static string TextInputPromptHeader {
            get {
                return ResourceManager.GetString("TextInputPromptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input range : 0 - 30.
        /// </summary>
        public static string TextInputPromptMessage {
            get {
                return ResourceManager.GetString("TextInputPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tile can set the system volume in one click. Input range : 0 - 30.
        /// </summary>
        public static string TextInputPromptTitle {
            get {
                return ResourceManager.GetString("TextInputPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value was not in a correct format.
        /// </summary>
        public static string TextInputPromptWarning {
            get {
                return ResourceManager.GetString("TextInputPromptWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number from 0 - 30.
        /// </summary>
        public static string TextInputPromptWarningValue {
            get {
                return ResourceManager.GetString("TextInputPromptWarningValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music is playing.
        /// </summary>
        public static string TextMusicIsPlaying {
            get {
                return ResourceManager.GetString("TextMusicIsPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string TextNotice {
            get {
                return ResourceManager.GetString("TextNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin volume to start screen.
        /// </summary>
        public static string TextPinVolume {
            get {
                return ResourceManager.GetString("TextPinVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Inception Inc.&quot;.
        /// </summary>
        public static string TextPublisher {
            get {
                return ResourceManager.GetString("TextPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string TextSettings {
            get {
                return ResourceManager.GetString("TextSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string TextShellToastTitle {
            get {
                return ResourceManager.GetString("TextShellToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully.
        /// </summary>
        public static string TextSuccessfully {
            get {
                return ResourceManager.GetString("TextSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string TextTutorialText1 {
            get {
                return ResourceManager.GetString("TextTutorialText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press &amp; hold to add shortcut on your start screen.
        /// </summary>
        public static string TextTutorialText2 {
            get {
                return ResourceManager.GetString("TextTutorialText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got It.
        /// </summary>
        public static string TextTutorialText3 {
            get {
                return ResourceManager.GetString("TextTutorialText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume adjust.
        /// </summary>
        public static string TextVolumeAdjust {
            get {
                return ResourceManager.GetString("TextVolumeAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Tiles/.
        /// </summary>
        public static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Main.xaml.
        /// </summary>
        public static string ViewMain {
            get {
                return ResourceManager.GetString("ViewMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Main.xaml?Shortcut=.
        /// </summary>
        public static string ViewMainExtend {
            get {
                return ResourceManager.GetString("ViewMainExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Navigation.xaml.
        /// </summary>
        public static string ViewNavigation {
            get {
                return ResourceManager.GetString("ViewNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Navigation.xaml?Shortcut=.
        /// </summary>
        public static string ViewNavigationExtend {
            get {
                return ResourceManager.GetString("ViewNavigationExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Settings.xaml.
        /// </summary>
        public static string ViewSettings {
            get {
                return ResourceManager.GetString("ViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Volume.xaml.
        /// </summary>
        public static string ViewVolume {
            get {
                return ResourceManager.GetString("ViewVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Volume.xaml?volume=.
        /// </summary>
        public static string ViewVolumeExtend {
            get {
                return ResourceManager.GetString("ViewVolumeExtend", resourceCulture);
            }
        }
    }
}
