//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STOP_Music.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STOP_Music.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _300x300 {
            get {
                object obj = ResourceManager.GetObject("_300x300", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _400x400 {
            get {
                object obj = ResourceManager.GetObject("_400x400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _691x336 {
            get {
                object obj = ResourceManager.GetObject("_691x336", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History.
        /// </summary>
        public static string AppBarClearHistory {
            get {
                return ResourceManager.GetString("AppBarClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickStop.
        /// </summary>
        public static string AppBarQuickStop {
            get {
                return ResourceManager.GetString("AppBarQuickStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string AppBarRating {
            get {
                return ResourceManager.GetString("AppBarRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just tap the tile and your music will be stopped, no need to even open the application! The Volume Bar will be cleared and the music controls removed from the volume bar and the lock screen. No more accidentally pressing the play button. .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your feedback here]
        ///
        ///
        ///---------------------------------
        ///Device Name: {0}
        ///Device Manufacturer: {1}
        ///Device Firmware Version: {2}
        ///Device Hardware Version: {3}
        ///Application Version: {4}
        ///---------------------------------.
        /// </summary>
        public static string FeedbackBody {
            get {
                return ResourceManager.GetString("FeedbackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to hear you didn&apos;t want to rate MyApp.
        ///
        ///Tell us about your experience or suggest how we can make it even better..
        /// </summary>
        public static string FeedbackMessage1 {
            get {
                return ResourceManager.GetString("FeedbackMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string FeedbackNo {
            get {
                return ResourceManager.GetString("FeedbackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Feedback .
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can we make it better?.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InceptionInc@live.com.
        /// </summary>
        public static string FeedbackTo {
            get {
                return ResourceManager.GetString("FeedbackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string FeedbackYes {
            get {
                return ResourceManager.GetString("FeedbackYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Background/.
        /// </summary>
        public static string ImageBackground {
            get {
                return ResourceManager.GetString("ImageBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Help/.
        /// </summary>
        public static string ImageHelp {
            get {
                return ResourceManager.GetString("ImageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Images/History.png.
        /// </summary>
        public static string ImageHistory {
            get {
                return ResourceManager.GetString("ImageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/notice.png.
        /// </summary>
        public static string ImageNotice {
            get {
                return ResourceManager.GetString("ImageNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this feature only available on DONATE version. Would you like get it ?.
        /// </summary>
        public static string MsgDonate {
            get {
                return ResourceManager.GetString("MsgDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like auto STOP Music when you tap tile ?.
        /// </summary>
        public static string MsgQUICKSTOP {
            get {
                return ResourceManager.GetString("MsgQUICKSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Music/QueHuongVietNam.mp3.
        /// </summary>
        public static string MusicQueHuongVietNam {
            get {
                return ResourceManager.GetString("MusicQueHuongVietNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Music/stop.mp3.
        /// </summary>
        public static string MusicQuickstop {
            get {
                return ResourceManager.GetString("MusicQuickstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/QuickStopTiles/QUICK400x400.png.
        /// </summary>
        public static string QUICKSTOP400 {
            get {
                return ResourceManager.GetString("QUICKSTOP400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/QuickStopTiles/QUICK691x336.png.
        /// </summary>
        public static string QUICKSTOP691 {
            get {
                return ResourceManager.GetString("QUICKSTOP691", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love you to rate our app 5 stars
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better!.
        /// </summary>
        public static string RatingMessage1 {
            get {
                return ResourceManager.GetString("RatingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You look to be getting a lot of use out of our application!
        ///
        ///Why not give us a 5 star rating to show your appreciation?.
        /// </summary>
        public static string RatingMessage2 {
            get {
                return ResourceManager.GetString("RatingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string RatingNo {
            get {
                return ResourceManager.GetString("RatingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying this app?.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate 5 stars.
        /// </summary>
        public static string RatingYes {
            get {
                return ResourceManager.GetString("RatingYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear history.
        /// </summary>
        public static string TextClearHistory {
            get {
                return ResourceManager.GetString("TextClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donate.
        /// </summary>
        public static string TextDonate {
            get {
                return ResourceManager.GetString("TextDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Inception.
        /// </summary>
        public static string TextInception {
            get {
                return ResourceManager.GetString("TextInception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string TextNotice {
            get {
                return ResourceManager.GetString("TextNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Stop.
        /// </summary>
        public static string TextQuickstop {
            get {
                return ResourceManager.GetString("TextQuickstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rating.
        /// </summary>
        public static string TextRatting {
            get {
                return ResourceManager.GetString("TextRatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string TextSetting {
            get {
                return ResourceManager.GetString("TextSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully.
        /// </summary>
        public static string TextSuccessfully {
            get {
                return ResourceManager.GetString("TextSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE KEEP APP RUNNING IN FOREGROUND,THIS APP WILL BE CLOSED WHEN TIMER ENDS.
        /// </summary>
        public static string TextWarning {
            get {
                return ResourceManager.GetString("TextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t close this app and run it under \nlockscreen while TIMER is activated 🙅.
        /// </summary>
        public static string ToastMessage {
            get {
                return ResourceManager.GetString("ToastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice !.
        /// </summary>
        public static string ToastTitle {
            get {
                return ResourceManager.GetString("ToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quickstop.
        /// </summary>
        public static string VarQuickstop {
            get {
                return ResourceManager.GetString("VarQuickstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timerinput.
        /// </summary>
        public static string VarTimerInput {
            get {
                return ResourceManager.GetString("VarTimerInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2.0.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Main.xaml.
        /// </summary>
        public static string ViewMain {
            get {
                return ResourceManager.GetString("ViewMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Quickstop.xaml?quickstop=.
        /// </summary>
        public static string ViewQuickstopExtend {
            get {
                return ResourceManager.GetString("ViewQuickstopExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Timer.xaml.
        /// </summary>
        public static string ViewTimer {
            get {
                return ResourceManager.GetString("ViewTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Timer.xaml?timerinput=.
        /// </summary>
        public static string ViewTimerExtend {
            get {
                return ResourceManager.GetString("ViewTimerExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Tutorial.xaml.
        /// </summary>
        public static string ViewTutorial {
            get {
                return ResourceManager.GetString("ViewTutorial", resourceCulture);
            }
        }
    }
}
